# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('kb', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[(b'OPEN', b'Open'), (b'RESOLVED', b'Resolved'), (b'REOPENED', b'Reopened'), (b'ONHOLD', b'On Hold')], default=b'OPEN', max_length=100)),
            ],
        ),
    ]
