# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='issue',
        ),
        migrations.AddField(
            model_name='comment',
            name='issue_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Issue'),
            preserve_default=False,
        ),
    ]
