# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_issuehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='issue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Issue'),
        ),
    ]
