# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
