# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_article_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.CharField(max_length=255)),
                ('fk', models.IntegerField(default=0)),
                ('model_kind', models.CharField(max_length=100)),
            ],
        ),
    ]
